name: CI/CD – Next.js on Vercel

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

env:
  NEXT_TELEMETRY_DISABLED: 1
  NODE_VERSION: 20

jobs:
  ci:
    name: Lint • Test • Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present

      - name: Build (sanity check)
        run: npm run build

  deploy:
    name: Deploy to Vercel (no prebuilt)
    needs: ci
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      # Let Vercel build in the right environment automatically

      - name: Deploy (Preview on PRs)
        if: github.event_name == 'pull_request'
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (Production on main)
        if: github.event_name == 'push'
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
